name: Build Waterfall
on:
  push:
    branches:
      - ver/1.18
      - feature/waterfall
  pull_request:
    branches:
      - feature/waterfall
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Patch on Java ${{ matrix.java }}
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./amethyst p
      - name: Build on Java ${{ matrix.java }}
        run: mvn clean install javadoc:javadoc -B
